name: Resolve \include{} statements in .tex files
author: lunaroyster
description: This action recursively resolves \include{} statements in .tex files to produce a single output file
inputs:
  entry:
    description: 'The .tex entry file'
    required: true
  out:
    description: 'The .tex output'
    required: true
runs:
  using: "composite"
  steps:
    - name: Resolve includes
      run: |
        python3 ${{ github.action_path }}/resolveIncludes.py ${{inputs.entry}} ${{inputs.out}}
      shell: bash